version: '3.8'

services:
  nginx:
    image: ghcr.io/${GITHUB_REPOSITORY}/tenants-nginx:latest
    container_name: tenants-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - tenants-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  tenants-network:
    name: tenants-network
    driver: bridge
    external: true

